language: java
jdk:
  - oraclejdk11

services:
  - docker

env:
  global:
    - DOCKER_COMPOSE_VERSION=1.27.4
    - DC=~/bin/docker-compose
    - DC_FILE=src/integrationTest/docker/docker-compose.yml

cache:
  directories:
    - $HOME/.gradle/caches/jars-1
    - $HOME/.gradle/caches/jars-2
    - $HOME/.gradle/caches/jars-3
    - $HOME/.gradle/caches/modules-2/files-2.1/
    - $HOME/.gradle/native
    - $HOME/.gradle/wrapper

before_install:
  - ./gradlew downloadDependencies
  - mkdir -p "$HOME/bin";
  - export PATH="$PATH:$HOME/bin";
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > $DC;
  - chmod +x $DC;

script:
  - ./gradlew check --stacktrace
  - sudo $DC -f $DC_FILE up -d rest-proxy-1 hdfs-datanode-1 hdfs-datanode-2 && sleep 15 && sudo $DC -f $DC_FILE up -d && ./gradlew integrationTest --stacktrace
  - sudo $DC -f $DC_FILE down -v
after_script:
  - ./gradlew sendCoverageToCodacy

deploy:
  - provider: releases
    api_key: ${GH_TOKEN}
    file_glob: true
    file:
      - build/libs/*.jar
    skip_cleanup: true
    on:
      tags: true
  - provider: script
    script: ./gradlew bintrayUpload
    skip_cleanup: true
    on:
      tags: true
